function randomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + Math.ceil(min);
}

function newRandom(type = 0){
    var int = randomInt(0, arrWords.length - 1);
    return arrWords[int][type];
}

var arrWords = [
	["Amount", "Swm"],
	["Angle", "Ongl"],
	["Area", "Arwynebedd"],
	["Ascending", "Esgyn"],
	["Bearing", "Beryn"],
	["Bounds", "Rhwymau"],
	["Calculate", "Cyfrifo"],
	["Certain", "Sicr"],
	["Chance", "Cyfle"],
	["Chart", "Siart"],
	["Column", "Colofn"],
	["Construct", "Adeiladu"],
	["Cube", "Ciwb"],
	["Data", "Data"],
	["Density", "Dwysedd"],
	["Dimension", "Dimensiwn"],
	["Edge", "Ymyl"],
	["Estimate", "Amcangyfrif"],
	["Evaluate", "Gwerthuso"],
	["Expand", "Ehangu"],
	["Face", "Wyneb"],
	["Factors", "Ffactorau"],
	["Find", "Canfod"],
	["Formula", "Fformiwla"],
	["Fraction", "Ffracsiwn"],
	["Frequency", "Amlder"],
	["Generate", "Cynhyrchu"],
	["Gradient", "Graddiant"],
	["Graph", "Graff"],
	["Identity", "Hunaniaeth"],
	["Internal", "Mewnol"],
	["Interpret", "Dehongli"],
	["Kite", "Barcud"],
	["Laws", "Cyfreithiau"],
	["Like", "Hoffi"],
	["Likely", "Tebygol"],
	["List", "Rhestr"],
	["Mean", "Cymedr"],
	["Measure", "Mesur"],
	["Median", "Canolrif"],
	["Mode", "Modd"],
	["Mutually", "Pawb"],
	["Negative", "Negyddol"],
	["Numerator", "Rhifiadur"],
	["Origin", "Tarddiad"],
	["Outcomes", "Canlyniadau"],
	["Parallel", "Cyfochrog"],
	["Places", "Lleoedd"],
	["Plan", "Cynllun"],
	["Plot", "Plot"],
	["Positive", "Positif"],
	["Powers", "Pwerau"],
	["Primes", "Cysefin"],
	["Product", "Cynnyrch"],
	["Quadrant", "Cwadrant"],
	["Range", "Ystod"],
	["Rational", "Rhesymegol"],
	["Recurring", "Cyson"],
	["Reflect", "Adlewyrchu"],
	["Reflex", "Atgyrch"],
	["Replace", "Disodli"],
	["Roots", "Gwreiddiau"],
	["Round", "Rownd"],
	["Rounding", "Talgrynnu"],
	["Sample", "Sampl"],
	["Scale", "Graddfa"],
	["Scatter", "Gwasgariad"],
	["Sector", "Sector"],
	["Segment", "Segment"],
	["Sequence", "Dilyniant"],
	["Series", "Cyfres"],
	["Share", "Rhannu"],
	["Simplify", "Symleiddio"],
	["Solution", "Ateb"],
	["Square", "Sgwar"],
	["Subject", "Pwnc"],
	["Symmetry", "Cymesuredd"],
	["Tally", "Tally"],
	["Tangent", "Tangiad"],
	["Term", "Tymor"],
	["Translate", "Cyfieithu"],
	["Union", "Undeb"],
	["Unknowns", "Anhysbys"],
	["Unlikely", "Annhebygol"],
	["Volume", "Cyfrol"],
	["Width", "Lled"]	
];